USE [master]
ALTER DATABASE [$(dbN)] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [$(dbN)] FROM  DISK = N'C:\BKP\$(bkpFileName)' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [$(dbN)] SET MULTI_USER

GO
